#!/bin/sh
# Renders Include/Config.php from the environment, then hands off to the image's
# normal entrypoint.
#
# Why this exists
# ---------------
# Config.php holds the database credentials and is NOT part of the image (upstream's
# release-context builder rejects any archive containing one, so no image can ship
# it). It normally gets written by the /setup wizard, which leaves it in the
# container's writable layer -- so recreating the container, i.e. any image
# upgrade, throws it away while the database volume survives. Verified on 7.7.1:
# `docker compose up -d --force-recreate crm` loses it and the app falls back to
# the wizard with all member data still present.
#
# Generating it here from .env makes the config declarative and survives upgrades.
# It also removes the browser wizard entirely: once Config.php exists, Bootstrapper
# creates the schema and the admin account on first request by itself (verified --
# 47 tables and the `Admin` user appear without any wizard step beyond the POST).
#
# An existing Config.php is left untouched, so mounting your own from the host
# still overrides this.
set -eu

CONFIG=/var/www/html/Include/Config.php

if [ -f "$CONFIG" ]; then
    echo "churchcrm: $CONFIG exists, leaving it alone"
else
    # ConfigLoader::validateDbPassword rejects an empty password, so fail here
    # with a clear message rather than at the first web request.
    for var in DB_SERVER_NAME DB_NAME DB_USER DB_PASSWORD URL; do
        eval "val=\${$var:-}"
        if [ -z "$val" ]; then
            echo "churchcrm: $var is required but empty. Check your .env." >&2
            exit 1
        fi
    done

    # var_export() handles quoting and escaping, so a password containing
    # quotes or backslashes cannot break out of the PHP string literal.
    php -r '
        $q = function (string $k, string $d = ""): string {
            $v = getenv($k);
            return var_export(($v === false || $v === "") ? $d : $v, true);
        };
        $php = "<?php\n"
            . "// Generated at container start from the environment. Do not edit.\n"
            . "// Re-created on every start, so it survives image upgrades.\n"
            . "\$sSERVERNAME = " . $q("DB_SERVER_NAME") . ";\n"
            . "\$dbPort = " . $q("DB_SERVER_PORT", "3306") . ";\n"
            . "\$sUSER = " . $q("DB_USER") . ";\n"
            . "\$sPASSWORD = " . $q("DB_PASSWORD") . ";\n"
            . "\$sDATABASE = " . $q("DB_NAME") . ";\n"
            . "\$sRootPath = " . $q("ROOT_PATH") . ";\n"
            . "\$URL[0] = " . $q("URL") . ";\n"
            . "error_reporting(E_ERROR);\n"
            . "require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . \x27LoadConfigs.php\x27);\n";
        if (file_put_contents("/var/www/html/Include/Config.php", $php) === false) {
            fwrite(STDERR, "churchcrm: could not write Config.php\n");
            exit(1);
        }
    '
    # Generated by www-data and read by www-data (Apache runs unprivileged), so
    # 0600 is sufficient. It holds the database password, so do not leave it
    # group/world readable.
    chmod 600 /var/www/html/Include/Config.php

    echo "churchcrm: generated $CONFIG from environment"
fi

# Upstream image entrypoint is `docker-php-entrypoint`, CMD `apache2-foreground`.
exec docker-php-entrypoint "$@"